### ISSUE TITLE
Request's Architecture

### ISSUE THREAD

**Issue by seanstrom** [request/request#1094]
Hey can some one give me a high level breakdown of request's architecture?
I basically want to get some point of views of how this software is perceived and how it actually works.
@mikeal

**Comment by Janpot** [comment]
Just stumbled across this thread and wanted to share something I worked on a few months ago. I've since abandoned the project, maybe I'll pick it up again some day, maybe not. It's basically a different approach on how to achieve a `request`-like library in a modular way. I started from a base module that implements the most basic stripped down http request I could think of. Then I build up all other functionality in the form of middleware. Just like libraries like express build up the server side functionality of http through middleware functions.
The idea here is that a middleware function receives a `request` object which it can alter at will (headers etc...). Then call a `next` function that calls all downstream middleware up until the basic request. After which the response object bubbles back up where it can be manipulated by the same middleware.
This way I was able to isolate all functionality for e.g. redirection, gzip, cookies into their own modules.
https://github.com/Janpot/kwest
https://github.com/Janpot/kwest-redirect
https://github.com/Janpot/kwest-cookies
https://github.com/Janpot/kwest-gzip
Now, I'm not saying this is a stable library and you should make `request` like this. I just wanted to share a way of looking at it that I didn't yet see in this thread. Which is mimicking the way we build http servers to the way we build http clients.

Glancing over my readmes I notice they are not ready and fully consistent so let me add an example here as well, this is how it worked:

```js
var kwest = require('kwest');
var kwestRedirect = require('kwest-redirect');
var kwestBodyparser = require('kwest-bodyparser');

var request = kwest()
  .use(kwestRedirect({ maxRedirects: 10 }))
  .use(kwestBodyparser());

request.use(function rejectErrors(req, next) {
  // You can also alter req here, like setting headers, etc
  return next(req).then(function (res) {
    // This lib was promise based, but that's ofcourse an implementation detail
    if (res.statusCode !== 200) {
      throw new Error('bad status');
    }
    return res;
  });

});

request({
  url: 'http://www.google.com'
}).then(function (res) {
  // do something with the response here
});
```

Again, not claiming this is better or saying you should do it this way, just want to spark some inspiration by showing a different approach. I found that this approach had its advantages.

I use `request` a lot in my day to day work (and love it) and the reason why I started exploring this `kwest` approach is that I often found myself needing things like "a http request that respects robots.txt" or "a http request that detects encoding and decodes text", etc... which IMO would be great candidates for a middleware/plugin like system.

**Comment by simov** [comment]
Thanks for sharing this @Janpot I'll take a look at it. Actually I had similar idea (too lazy to search for the exact thread and comment) still a code in that direction is more valuable that just the idea :+1:

**Comment by Freyert** [comment]
+1 for @Janpot 's idea all the way! Breaking apart logic into modules would be tremendous. It's definitely a reason `express` is so popular.

I might point out though, that most of what's described by @Janpot can be achieved with a function like [_.compose](https://lodash.com/docs#flowRight), [R.compose](http://ramdajs.com/docs/#compose), or [R.composeP](http://ramdajs.com/docs/#composeP). 

I submit my vote for the decomposition though, as I have definitely struggled with _redirects_ and _cookies_. From my limited debugging experience I've gleaned it's very difficult to trace the route from my request to how redirect requests are formed.

Just to add another potential perspective for how one could decompose `request`, I've been playing around with a small redirect function who's interface looks something like this:

```javascript
let j = request.jar();
let r = request.defaults({
  jar: j
});
let inputs = {
  method: 'GET',
  url: 'https://www.google.com'
};
redirect(iteratee, r, inputs, cb);
```

Where `iteratee` is a function that will tell a redirect to stop or continue (probably also needs to be able to modify the redirect request). And `cb` is the function that is called when redirects are finished or an error occurs. Stuck with the ol' node callback style to support more platforms.

**Comment by seanstrom** [comment]
In general I would like to see things be more composable, I feel like the internal structure may want to start implementing the state machine as a series of composed functions. Then it should be pretty easy to add any official third party hooks for composition. @Freyert @simov Thoughts?

**Comment by Freyert** [comment]
I'm in the party of less is more.  I think not implementing a middleware stack in `request` will give it an edge in the maintenance department. I think also, especially with `koa` being around these days, that people will have opinions on how the stack should work. Should I manage state with `Promises`, `calbacks`, or `generators`? State _sucks_ and I would prefer to work with something that stays away from it and let's me make that decision. Especially since JS's feature set is so volatile these days.


Ideally I would be able to do something like below:
```javascript
//requestAsync is a customized promise I wrote myself.
R.composeP(parse, toJSON, requestAsync(R.__))
```

But also be able to use `request` for piping responses. Conceivably someone will create a `generator` version of `R.compose` and anyone who can take advantage of that can and `request` won't have to do any maintenance or bump versions. Therefore, less is more.

**Comment by seanstrom** [comment]
I see what you're saying about not having middleware. Most of the suggestions around breaking Request end up showing some kind of middleware system. That said I would prefer having a system where all the features that could be built on top of request would be modeled like function that can compose. Which is what I believe you're describing right?

**Comment by simov** [comment]
Pseudo code is fine, but reality is different, that's why we have the code base as it is ATM. While I'm not saying that the current code base is structured good enough, there are certain design patterns that simply won't work for building HTTP client. And you can't know that for sure before you actually try and build one with a good amount of features in it.

Also there is a huge difference between refactoring and rewrite. IMO refactoring isn't possible for the current code base. There are too much constraints to look for, the biggest one being the huge user base relying on almost every hack/fix/decision that you can find in the code base.

Mikeal started [such rewrite](https://github.com/request/request/commit/1bb95d1d58b5d02a62f089aefafd08e4562843af) two years ago, and got nowhere. Also it's interesting to see the [http-duplex-client](https://github.com/isaacs/http-duplex-client/blob/master/client.js) which is Streams2 compatible.

I meditated a bit on the above commit, and at the end I decided that I have a different vision about how the HTTP client should be built. So about a month ago I started to put some code aside trying to assemble a working HTTP client. I'm using the HTTP duplex client mentioned above, slightly modified, also it turned out that some parts of that implementation doesn't work as expected, namely the `_write` method always returns `true` even though the underlying `http.clientRequest` write returns `false` for example.

Anyway, what I'm trying to say is that we should keep the current version 2.x working as it is, that includes adding of new features and fixes. Probably migrate to Streams2 at best, which will require rewrite of a few external modules as well.

Anyone is free to start their own rewrite from scratch. Of course it will be a huge effort to implement all of the request's features, but at least you can see them.

**Comment by Freyert** [comment]
Yeah doing a total rewrite would be a pain, and refactoring also a pain. As it stands now, the ideas I'm throwing out are probably better off for user land (Which you also see with  `express`). Rewriting basic redirect logic is a fairly simple task and it's pretty easy to do what I'm talking about on your own.

It makes me curious though about what the original intent of this project was? What problem is it solving? If I like breaking off different pieces of logic like I am, should I just call it quits and start using the plain old `http` module or am I getting something from `request`? (Not to be contentious, I really do love the work that's been put into `request`, but I'm just curious to know if I'm not using it to it's full potential.)

**Comment by simov** [comment]
Yep, the API you are proposing should be implemented as a request wrapper. Good example is [Purest](https://github.com/simov/purest) which only configures request through it's API, it doesn't handle anything HTTP specific directly.

As for request, its purpose is to implement some of the common features that you expect an HTTP client to have. The core HTTP module mainly parses the raw HTTP messages and handles the TCP sockets for you, through its Agent class. Well that's probably overly simplified but it's definitely not a full featured HTTP client, like a browser for example.

Some of the features currently in core were first implemented in request, like the [forever-agent](https://github.com/request/forever-agent), also at that time there were no Streams2 and common Duplex stream interface.

But that's not that important either, here is what I'm currently outlining as requirements for my own experiment:

- the client can be used seamlessly like the bare core HTTP module
- each feature should be enabled by option, there is no defaults except the ones you get from core
- each option enables default implementation, you can plug in your own via function
- each default implementation is a separate module set as dependency in the consumer project

I think that's for now. Oh and btw the redirect logic with all of the request features is not the easiest thing to implement.

**Comment by simov** [comment]
https://github.com/request/request/issues/1982
