### ISSUE TITLE
Problem with http-https redirection behind proxy: Error: tunneling socket could not be established, cause=Parse Error

### ISSUE THREAD

**Issue by rkrejcii** [request/request#1357]
Hi.

I have problem using following code (GET request via authorised proxy) in the case of redirection from HTTP to HTTPS site. When I for example request 
<code>http://twitter.com</code>
I'm getting error message
<code> { [Error: tunneling socket could not be established, cause=Parse Error] code: 'ECONNRESET' }</code>

Redirection is taken in account as the <code>followRedirect</code> callback returns following <code>response.headers</code>:

<pre>
{ 'content-length': '0',
  date: 'Thu, 15 Jan 2015 15:01:14 UTC',
  location: 'https://twitter.com/',
  server: 'tsa_b',
  'set-cookie': [ 'guest_id=v1%3A142133407487424756; Domain=.twitter.com; Path=/; Expires=Sat, 14-Jan-2017 15:01:14 UTC' ],
  'x-connection-hash': 'fd168ae941d6db2cef7c0ddc48826e57',
  'x-response-time': '2' }
</pre>

The problematic code (sensitive info hidden):

<pre>
var request = require('request');

var agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A";

var proxyPort = "XXX";
var proxyLogin = "XXX";
var proxyPwd = "XXX";

var proxyIP = "XXX.XXX.XXX.XXX";

var proxyURL = 'http://' + proxyIP + ":" + proxyPort;
var auth = 'Basic ' + new Buffer(proxyLogin + ':' + proxyPwd).toString('base64');

var url = "http://twitter.com/";

request({
        method: 'get',
        url: url,
        proxy: proxyURL,
        timeout: 10000,
        tunnel: true,
        sendImmediately: true,
        followAllRedirects: true,
        followRedirect: function(response){console.log(response.headers); return true;},
        headers: {
            'User-Agent': agent,
            "Cache-Control" : "no-cache",
                'Proxy-Authorization': auth,
        }
    }, function(err, response, body){
        if (err) {
            console.log(err);
        } else {
            console.log(response.statusCode);
        }
    }
)
</pre>

Thanks for every help.

**Comment by nylen** [comment]
so, you're getting a redirect to `https://twitter.com/`, what happens if you make that your URL instead of `http:` ?

also, a standalone test case that reproduces the problem would be really helpful.  see [`test-tunnel.js`](https://github.com/request/request/blob/0e22b30f7bdb31d87ceee33f076adb684bca07ad/tests/test-tunnel.js) for examples of how to do this.

**Comment by Freyert** [comment]
Getting this same error as well. My question is where can we find this error message in the `request` library?

**Comment by Freyert** [comment]
@rkrejcii figure out what was causing mine. It's an error when it tries to parse the headers in my case. I'm using `cradle` and it sets `Content-Length` instead of not caring, or letting `request` handle it, or using `content-length` instead. When I remove the header it works great.

Thoughts now are, perhaps I need to `whitelist` Content-Length. Perhaps only whitelisted headers are parsed.

**Comment by Freyert** [comment]
Well, `content-length` is already on the whitelist.

**Comment by simov** [comment]
The `content-length` header was removed from the whitelist here https://github.com/request/request/pull/1915 though this fix is not published yet. The whitelist contains headers that are allowed to be sent to the proxy server.

**Comment by jachstet-sea** [comment]
On what operating systems are you all on? Could you please check if my comments in https://github.com/npm/npm/issues/3084#issuecomment-272437923 are usefule to you?
