### ISSUE TITLE
Upper Buffer Limit

### ISSUE THREAD

**Issue by acidhax** [request/request#1403]
Is it possible to create a maximum Buffer size, so it must be consumed before continuing to fill the rest of the buffer?
Is it also possible to be able to pause a data receive?

It's not documented and I would like to avoid >1gb files using memory, or needlessly writing to disk.

**Comment by nylen** [comment]
You'll want to use the streaming interface for these tasks, so this becomes a question about Node.js streams rather than `request` specifically.  Something similar has been discussed before though, see #1083.  As far as pausing, I'm not sure if [the `pause` method](http://nodejs.org/api/stream.html#stream_readable_pause) will actually stop data from being buffered, I doubt it.

**Comment by acidhax** [comment]
So essentially request can't pause incoming data?
I suppose a hybrid in-memory -> filesystem stream will have to do. I don't like it, but such is life.

**Comment by nylen** [comment]
I'm honestly not sure, it's worth a try to call `pause()` on a `Request` object.  It looks like that will go all the way back to the [socket `pause` method](http://nodejs.org/api/net.html#net_socket_pause).

You'll probably have better luck asking this as a Node.js streams question on StackOverflow - whatever solution you come up with isn't going to be specific to `request`.

If you do find something that works, let us know because it would make a good usage example :)
