### ISSUE TITLE
Array parameters in the query string produce numeric indexes

### ISSUE THREAD

**Issue by gajus** [request/request#1473]
```js
request({uri: 'http://foo.com', qs: {filter: ['a', 'b']}});
```

Will make a request to http://foo.com?filter[0]=a&filter[1]=b. It should be making a request to http://foo.com?filter[]=a&filter[]=b.

**Comment by simov** [comment]
Hi @gajus did you tried the `useQuerystring` option?

> useQuerystring - If true, use querystring to stringify and parse querystrings, otherwise use qs (default: false). Set this option to true if you need arrays to be serialized as foo=bar&foo=baz instead of the default foo[0]=bar&foo[1]=baz.

**Comment by gajus** [comment]
`useQuerystring` is even worse, because it does not produce `[]` as part of the name.

**Comment by simov** [comment]
It seems that this issue was recently addressed in the qs module https://github.com/hapijs/qs/pull/70

So the syntax would be (currently undocumented, scheduled for version 2.4.0)

```bash
> qs.stringify({arr:['a', 'b']}, {})
'arr%5B0%5D=a&arr%5B1%5D=b'
> qs.stringify({arr:['a', 'b']}, {arrayFormat: 'indices'})
'arr%5B0%5D=a&arr%5B1%5D=b'
> qs.stringify({arr:['a', 'b']}, {arrayFormat: 'brackets'})
'arr%5B%5D=a&arr%5B%5D=b'
> qs.stringify({arr:['a', 'b']}, {arrayFormat: 'repeat'})
'arr=a&arr=b'
```

Once it's published we should improve the `qs` option key to be able to receive additional options (just like the `multipart` key) As for the chain API it won't be a problem I guess.

Lets keep this issue open for now.

**Comment by simov** [comment]
`qs@2.4.0` just got published, assigning this one to myself, I'm going to introduce a `qsOptions` option, I think it will be cleaner in our case.
