### ISSUE TITLE
Error while trying to get URI which begins with "//"

### ISSUE THREAD

**Issue by eugeneff** [request/request#1513]
Greetings!

When I try to make a request to URI, which begins with double slashes - I see an error. Here is my code:

```javascript
var fs = require('fs'),
    request = require('request').defaults({jar: true});

request('//nebula.wsimg.com/e25472c4310e76d1b31796c5d6b1443c?AccessKeyId=61CD4C5E14DE8D87B277&disposition=0&alloworigin=1')
    .pipe(fs.createWriteStream('img.png'));
```

And here is the error: 
```
events.js:72
        throw er; // Unhandled 'error' event
              ^

Error: Invalid URI "//nebula.wsimg.com/e25472c4310e76d1b31796c5d6b1443c?AccessKeyId=61CD4C5E14DE8D87B277&disposition=0&alloworigin=1"
    at Request.init (/path/node_modules/request/request.js:413:31)
    at new Request (/path/node_modules/request/request.js:264:8)
    at request (/path/node_modules/request/index.js:50:10)
    at /path/node_modules/request/index.js:141:14
    at Object.<anonymous> (/path/dist/app.js:10:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Am I doing something wrong, or is this a bug/feature?
If this is a feature, which protocol should be choosen for such kind of links?

**Comment by froatsnook** [comment]
Requesting `//` URLs only works from browsers because it can take the protocol from the current location.  So if the browser bar says "https://yoursite.com", then a request to "//nebula.wsimg.com" will request "https://nebula.wsimg.com", whereas if the browser bar says "http://yoursite.com", then it would go to "http://nebula.wsimg.com".  So either pick "http" or "https" depending on what nebula.wsimg.com expects.  My guess is that either would work!  Try them both and see which works :).

**Comment by eugeneff** [comment]
Makes sense, thanks.
