### ISSUE TITLE
qsStringifyOptions is not correctly forwarded to querystring.stringify

### ISSUE THREAD

**Issue by limbo-lab** [request/request#1593]
qs.stringify has signature (obj[, options]), while querystring.stringify has signature (obj[, sep][, eq][, options]) and `seq', `eq' can not be omitted.

**Comment by simov** [comment]
Yep, it seems like it, although in my understanding of the syntax it shouldn't be that way. Also we have tests only for the `qs` module. What do you propose? I'm for removing the support for `querystring` from the docs althogether, because `sep` and `eq` will be just unnecessary complication to implement and then reason about.

**Comment by limbo-lab** [comment]
querystring provide options for parsing/stringifying using specific charset encoding, while qs, it assumes that utf-8 is the only encoding.
This is an example found in node.js docs.

```js
querystring.parse('foo=bar&baz=qux&baz=quux&corge')
// returns
{ foo: 'bar', baz: ['qux', 'quux'], corge: '' }

// Suppose gbkDecodeURIComponent function already exists,
// it can decode `gbk` encoding string
querystring.parse('w=%D6%D0%CE%C4&foo=bar', null, null, { decodeURIComponent: gbkDecodeURIComponent })
// returns
{ w: '中文', foo: 'bar' }
```

**Comment by simov** [comment]
Thanks, good to know, however my point was a bit different. My question was how do you propose to implement those 3 parameters for querystring `[, sep][, eq][, options]` in case we allow only an options object atm, the `qsStringifyOptions`?

Generally that's a problem with lots of APIs that use parameters instead of object for parameters.
