### ISSUE TITLE
attach extra data into request of req.pipe(request.(...))

### ISSUE THREAD

**Issue by zyf0330** [request/request#1612]
How can I use req.pipe(request.(...)) and attach some extra data into request?
if I put it by form,error occurs with info 'write after end'.

**Comment by simov** [comment]
@zyf0330 can you provide a short code example to reproduce that behavior?

**Comment by zyf0330** [comment]
var form
req.pipe(request.post(URL,{form:form},...))

like this,but this word will occur error.
form is the extra data I want to attach to original req

追随
2015年5月29日 23:03于 "simo" <notifications@github.com>写道：

**Comment by zyf0330** [comment]
can you help me？

**Comment by simov** [comment]
@zyf0330 see https://github.com/request/request/issues/1616

In case you really do need to post some other `form` parameters, you probably won't need to pipe `req` to `request` because the `req` itself might be closed before you ever reach to the internal `write` in request. You can just create a new `request` instead:

```js
var body = req.body
body.other = 'stuff'
request.post(url, {form:body}).pipe(res)
```
