### ISSUE TITLE
Documentation missing for `agent` option

### ISSUE THREAD

**Issue by triccardi-systran** [request/request#1669]
`request` accepts a http/https Agent as `agent` option, but it's not documented.
What is documented is how to pass a pool of agents as `pool` option, but the code first checks if `self.agent` exists before using `self.pool` to get the http agent:

https://github.com/request/request/blob/2ca06330c9e8d438b07c9efd9a077303d2e59ec8/request.js#L486-L490

This should be documented & tested, or it should be removed... Otherwise we cannot rely on it.

**Comment by simov** [comment]
I agree there are other options missing from the docs as well, like `agentClass` and `agentOptions` mentioned here #1637

**Comment by simov** [comment]
@triccardi-systran see https://github.com/request/request/issues/1671

**Comment by tvdstaaij** [comment]
It sure seems to work, I just passed in a `https.Agent` object with the `keepAlive` option set to `true` (Node 0.12) and verified using an external TCP analysis tool that the connections are kept alive and reused, while this is not the case when the custom agent is not passed in.

This is a very useful feature but it took me over an hour of googling and analyzing source code to find it, so seconding the documentation request. I also suggest updating the documentation for `pool` so that the differences and use cases for the two are made clear.
