### ISSUE TITLE
CSRF Token missing in response

### ISSUE THREAD

**Issue by nyrrrr** [request/request#1722]
When a "fetch" request is sent via the request module, the response object does not contain a x-csrf-token field.

**Comment by simov** [comment]
Can you provide a short code example that reproduces the bug?

**Comment by nyrrrr** [comment]
app.use("/", function (req, res, next) {
         options = {
        'url': sDestination + req.url,
             'ca': cas,
             'jar': true,//jar,
            'strictSSL': true,
            'headers': {
        accept: '*/*'
            }
        };
        request(options, function (err, response, body) {
        if (err) { 
         console.error(err);
         }
        else {
         if (typeof req.headers['x-csrf-token'] === "string") {
        console.log("#1 " + (typeof req.headers['x-csrf-token'])); // string
         console.log("#2 " + (req.headers['x-csrf-token'])); // "Fetch"
         console.log("#3 " + (typeof response.headers['x-csrf-token'])); // undefined
         }
         }
        }).pipe(res);
    }

**Comment by simov** [comment]
I still can't use this code to reproduce anything, but if the server sends the `csrf` header, most certainly it will be available in the response.

**Comment by nyrrrr** [comment]
for reproducing the error you'd need a server requiring csrf auth.
what is it that you need from me?
when I query the server directly I will receive a x-csrf-token in the response. when I use nodejs and the request plugin as proxy, the response won't contain a token field.

**Comment by simov** [comment]
Ok, my point was that I need a working code example to reproduce it. I can't determine with certainty what your problem is just by looking at your code snippet, and I certainly can't run it.

**Comment by colmonty** [comment]
I'm seeing similar issues.

I can see a `set-cookie` header in my initial GET response, giving me the JSESSIONID to use in subsequent POST/PUT/DELETE requests.  However, that cookie never actually gets added to the jar.

I've written code to manually add the cookie, but the API I'm hitting tells me the CSRF is incorrect, but I'm almost sure this is because it hasn't received a JSESSIONID cookie.

There's some confusion over `jar:true` for a 'global' jar, or actually having a global variable at the top scope of my script: `var cookieJar = request.jar()`.  If I use `jar:true`, I don't appear to have any way to get at my cookies so I can pull out my CSRF value and add it to a header.  Yet if I use my `cookieJar` variable, the set-cookie headers from the initial response never actually get added to the cookie collection.

**Comment by Dipika-Baad** [comment]
I am facing the similar issue but in my case I checked the sent request header while authenticating & captured response header(using firebug) from which I see CSRF Token in request header but not in response header 'set-cookie' that is why I am not able to extract that token for further requests.

**Comment by fofiedelly** [comment]
solved any how ? i'm facing the same issue.....

**Comment by nyrrrr** [comment]
sorry, I cannot even properly recall the issue. It's been a while
