### ISSUE TITLE
Failed to execute 'fetch' on 'Window', Browserify, Chrome

### ISSUE THREAD

**Issue by ivitivan** [request/request#1802]
I'm getting an error executing this example in chrome 45.0.2454.101 with browserify:
```js
var request = require('request');
request('http://www.google.com', function (err, res, body) {
  console.log('err', err);
})
```
The error:
```
TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from //www.google.com:80/
```
Is there a way to make it work?
Thanks!

**Comment by simov** [comment]
You have to pass the protocol:

```js
var request = require('request');
request('http://www.google.com', {protocol:'http:'}, function (err, res, body) {
  console.log('err', err);
})
```
I'm not very familiar with the browserify's internals, so I'm assuming something has changed recently.

**Comment by TimBeyer** [comment]
@simov just ran into this problem too. The problem is that `request` isn't properly setting all data from `uri` on itself, especially when passed an object.

When setting up the `self` object passed to the request, `protocol` is not included.

As another example, `path` is handled but using `pathname` only leads to having no path at all.
This might be less of an issue though, because this will usually not happen when parsing an actual URL, only when manually creating the object and forgetting about `path`

**Comment by simov** [comment]
The only way around that is to [format](https://nodejs.org/api/url.html#url_url_format_urlobj) the URL first, if the user passes an object, and then parse it again. Having to deal with issues regarding this problem over and over again is just annoying.

**Comment by TimBeyer** [comment]
@simov the only difference that would make is hitting https://github.com/request/request/blob/a7f7e75e9962cf5b4a06ade9269e5ae10c2f57ce/request.js#L248-L250, at which point things continue just the same.
My proposal wold be to add `self.protocol = self.uri.protoco;l` after https://github.com/request/request/blob/a7f7e75e9962cf5b4a06ade9269e5ae10c2f57ce/request.js#L730 so that `protocol` is available on the toplevel object. That's exactly how `httpModule.request` expects things.

The cleaner solution might be to not just do `var reqOptions = copy(self)` but to construct exactly the object that `http` expects for options instead of doing a clone of the whole request object.

I just wasn't sure whether there might be any negative impact or whether I've overlooked something, else I'd PR this change directly.

**Comment by simov** [comment]
> The cleaner solution might be to not just do var reqOptions = copy(self) but to construct exactly the object that http expects for options instead of doing a clone of the whole request object.

http + https I assume

It is the cleaner solution and it won't affect anything else. But for the time being adding just the protocol property would probably be enough. And a test - the property should be available after the request was started.

**Comment by emschwartz** [comment]
I'm also seeing this issue while using request + webpack for a Chrome extension. Because of this bug it replaces the protocol with `chrome-extension://` causing all outgoing requests to fail
