### ISSUE TITLE
Request changes the order of headers on a redirect

### ISSUE THREAD

**Issue by ghun** [request/request#1901]
It seems when i do a new request HOST is the first header, but on redirects it is last. Have you noticed this?

**Comment by simov** [comment]
Is this really a problem?

**Comment by ghun** [comment]
Quoting this book: http://webbotsspidersscreenscrapers.com/ - "If done poorly, form emulation can get webbot designers into trouble because poorly designed form emulators may make errors that are impossible for a person to make using a standard browser." I guess same principles would apply for redirects, no?

**Comment by simov** [comment]
> form emulation

What is that?

Also how is that related to headers order?

**Comment by ghun** [comment]
Here's another quote that may make it more clear: "A poorly designed
webbot may leave strange records in the log files that servers use to track web
traffic and detect hackers."

**Comment by simov** [comment]
> The conspiracy is too damn high! 

I see you like quotes, but still I'm not sure what the problem really is regarding this module, and what exactly do you suggest. Can you elaborate?

**Comment by ghun** [comment]
Basically i'm trying to make my request look like it came from a browser, but if the headers are swapped around on redirects it's a give away

**Comment by simov** [comment]
Do you have any proofs that the headers order matters? Like RFC specification or something? 

I think you should be more concerned with headers being present and their values being the correct ones ,instead of their order being in one way or another. The only possible way for the server to know your headers order is to make full text search in the raw TCP message, or put them in array for some reason, which is highly unlikely IMO.

**Comment by ghun** [comment]
I see, i guess I won't worry about it then. Thanks for your help.
