### ISSUE TITLE
promise support

### ISSUE THREAD

**Issue by ihailong** [request/request#1935]
hi masters: since node 4+ support promise natively, is there any plan to support promise request? thanks for your great job.

**Comment by simov** [comment]
You should probably ask here https://github.com/request/request-promise

**Comment by wearhere** [comment]
I don't suppose you'd reconsider this now that native async/await support has landed in Node 7? Many companies will begin using promises now (if they're not already) and that will only accelerate when Node 8 goes LTS in the fall.

**Comment by mikeal** [comment]
Nothing has really changed, there's already a return value (the stream) and so you need a different library if your intent is just to use the buffering interface as a promise, which is https://github.com/request/request-promise

**Comment by wearhere** [comment]
I admit I am not sure how the library could cleanly return promises when it already returns streams. But the library does officially acknowledge the desire to retrieve the response as a buffer vs. a stream, by supporting callbacks—the authors did not relegate that convenience to a peer library. Perhaps a per-request option could be added to return a promise vs. a stream?

`request-promise` is deficient in a few ways. The first is that you still have to use `request` alongside it if you _sometimes_ want to handle the response as a stream. It's also another library to install, that has to be kept in sync with request. It also uses Bluebird rather than native promises. I'm aware that https://github.com/request/request-promise-native exists, but that doesn't even have its own documentation, rather referring you back to https://github.com/request/request-promise and then to https://github.com/request/request.

**Comment by FredKSchott** [comment]
I think it would be useful to add a note about promise support in the README. Right now we expect users to go out and find request-promise and other alternative interface libraries on their own (without knowing that they even exist).

Any objections to a PR to add a note?

**Comment by mikeal** [comment]
> I think it would be useful to add a note about promise support in the README

That's a great idea.
