### ISSUE TITLE
Node security advisory issued for Hawk ~3.1 dependency

### ISSUE THREAD

**Issue by Jon-Biz** [request/request#2020]
>Specifically crafted long headers or uris can cause a minor denial of service when using hawk versions less than 4.1.1.

https://nodesecurity.io/advisories/77

Relevant PR - #1891

**Comment by joeycozza** [comment]
While the PR is relevant, it only puts Hawk to 4.0.0 Like you said Job-Biz, Hawk needs to be 4.1.1 to resolve the nsp advisory.

**Comment by simov** [comment]
Good to know, but like I said in #1891 we are not ready to drop support for Node < 4 yet. Anyone is free to update its Hawk version manually. 

The problem here is the hard dependency, only a small portion of our users are using hawk anyway. BTW the dependency problem is fixed in the [rewrite](https://github.com/request/core).

We can add a notice in the readme if that sounds good to you.

**Comment by lumberj** [comment]
> Anyone is free to update its Hawk version manually.

This doesn't seem to work when `hawk` is two or more dependencies down the chain. For example, I have a project that depends on the latest `babel-cli`, which depends on `request`, which depends on `hawk`. Explicitly installing hawk@4.1.1 doesn't work, because request will install it's own version. I've tried installing things in various orders and can't make it work.

```
 babel-cli@6.4.5 > request@2.67.0 > hawk@3.1.2     
```

**Comment by simov** [comment]
Yes, scratch that. Do you actually use hawk in your application? Because I bet babel-cli does not. If that's the case then it doesn't matter. Just check if the `hawk` option is used anywhere in your code.

**Comment by simov** [comment]
Ok, read this by Eran Hammer himself:

> Use https://github.com/hueniverse/hawk/tree/v3.1.x instead of master
> Also, note that this doesn't affect any request user. It could affect people using hawk on the server to protect services but not anyone using it to make requests.
[source](https://github.com/hueniverse/hawk/pull/170#issuecomment-173300935)

So it turns out that the security fix is applied in version 3.x and it's related only to the server implementation of hawk.

**Comment by remy** [comment]
@simov [my PR](https://github.com/hueniverse/hawk/pull/171) got merged into hawk releasing hawk@3.1.3 which closes the vulnerability, which also means that request will automatically benefit from the fix (since it depends on `hawk@~3.1.0` so it'll match on 3.1.3).

**Comment by simov** [comment]
Yep, I know, thanks for taking the time to fix it.

**Comment by remy** [comment]
You're welcome :)

**Comment by lumberj** [comment]
So we're just waiting for the advisory to be updated? https://nodesecurity.io/advisories/77
