### ISSUE TITLE
Request pipe keeps a wrong header

### ISSUE THREAD

**Issue by acorbel** [request/request#2138]
Hi,

I've built a small app which downloads from a url and upload to another. Here is my code:

```
var downloadRequest = {
    url: downloadUrl,
    method: 'GET',
    headers: {Authorization: 'Bearer bearertoken'}
}
var uploadRequest = {
    url: uploadUrl,
    method: 'PUT',
    headers: {}
}
request(downloadRequest).pipe(request(uploadRequest));

```

So it is very simple but my first request needs authorization so it contains an Authorization header (Bearer) and the second one does not. However, this header Authorization line is still present during the pipe and blocks the upload request (Authorization header is not allowed).

I've tried the following code which does not work:

```
request(downloadRequest)
              .on('response', function(resp) {
                delete resp.headers['Authorization'];
              })
```

Node version: 4.2.1
Request version: 2.69.0

Do you deal with this issue too?

**Comment by andrey-aleshkov** [comment]
Have same problem

**Comment by a-covar** [comment]
I have the same issue

**Comment by anelmu** [comment]
Having the same problem, any solution for this?

**Comment by vnenkpet** [comment]
Having the same problem.

It also seems the *response* headers from the first request are kept as *request* headers to the second request.
```js
request(downloadUrl).pipe(request.put(uploadUrl);
```
this for one breaks if you're using something as AWS pre-signed URLs with something like the following message:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>AccessDenied</Code>
<Message>There were headers present in the request which were not signed</Message>
<HeadersNotSigned>x-amz-request-id, x-amz-id-2</HeadersNotSigned>
<RequestId>[*****]</RequestId>
<HostId>[*****]</HostId>
</Error>
```
Since `x-amz-request-id` and `x-amz-id-2` are headers from the *response* from `downloadUrl`, that are passed as request headers to the *request* to `uploadUrl` that doesn't accept these, which definitely should not happen or there should at least be a way to override it.
