### ISSUE TITLE
redirect request target url error

### ISSUE THREAD

**Issue by mantou132** [request/request#2216]
redirect request target url none response;

``` javascript
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ETIMEDOUT
```

**Comment by mantou132** [comment]
Because I misspelled cause no error handling.
I'm sorry

**Comment by simov** [comment]
From [CONTRIBUTING.md](https://github.com/request/request/blob/master/CONTRIBUTING.md):


## Submitting an Issue

1. Provide a small self **sufficient** code example to **reproduce** the issue.
2. Run your test code using [request-debug](https://github.com/request/request-debug) and copy/paste the results inside the issue.
3. You should **always** use fenced code blocks when submitting code examples or any other formatted output:
  <pre>
  ```js
  put your javascript code here
  ```

  ```
  put any other formatted output here,
  like for example the one returned from using request-debug
  ```
  </pre>

If the problem cannot be reliably reproduced, the issue will be marked as `Not enough info (see CONTRIBUTING.md)`.

If the problem is not related to request the issue will be marked as `Help (please use Stackoverflow)`.
