### ISSUE TITLE
request always throwing 200 over https

### ISSUE THREAD

**Issue by akashnimare** [request/request#2302]
``` javascript
var request = require('request');
request({url:'https://akashnimare.in/static/audio/zulip.ogg', strictSSL:false}, function (error, response, body) {
    console.log(response.statusCode)
})
```

even though the file does not exists. It should show 404. Where I am going wrong?

**Comment by KpjComp** [comment]
The URL you have given is returning 200..

It's just the server side is saying 404, but the return is actually 200.
So the problem is not request, but the server side.  It's not throwing a 404..

In fact the initial response is a 302, redirect, that redirects to a page that says 404, but in fact is returning a 200,.  You might want to contact HostGator about this, they might be an option not to do 404 redirect, but just return 404 response instead.
