### ISSUE TITLE
Using the 'body' of the response outside the callback?

### ISSUE THREAD

**Issue by donjae** [request/request#2317]
```
var result = ''
var data = request.get('https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=' + token, {json: true, encoding: undefined}, (error, response, body) => {
             if (!error && response.statusCode == 200){
                 result =+ body;
             }
         })
```

I'm trying to use the request module in attempt to receive a JSON object/response from google api, and **_use the body of the response outside of the request callback._** 

I've tried:
1. creating outer functions for a callback 
2. pushing the body data to a variable outside the scope 
3. using a concat module to collect the stream
4. returning the body
5. parsing the response

No clue what I need to do. I think it has to do with the body being a buffer and can't be save to a variable outside the scope? Can anyone help?

**Comment by scotttrinh** [comment]
Are you using that exact code? `=+` is not an operator, it's `+=`. At any rate, sounds like you might need some help understanding how async Javascript works. There isn't a way to get to that data "outside" of the callback, that's what the callback is for. If it looks crazy, that's just the nature of using callbacks. There are other mechanisms for dealing with async code (`Promise`s, `async`/`await`, etc), but for vanilla ES5 Javascript, that's just what it looks like:

```js
var googleApiRequest = request.get(
    'https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=' + token,
    { json: true, encoding: undefined },
    (error, response, body) => {
        // You can use body here, so put the logic that needs it here.
    }
);
```

As you might be able to guess, this style can make your code very nested. Since it seems you're already using some ES6/2015 (arrow functions), check out `Promise`s for a (arguably) flatter structure. https://github.com/request/request-promise
