### ISSUE TITLE
Malformed host header when accessing a docker daemon

### ISSUE THREAD

**Issue by manast** [request/request#2327]
This may not be a bug in request, and I would be happy to report it to the docker team if that is the case. The thing is that after upgrading to the latest version of docker (1.12), when I tried to connect to the daemon using unix domain sockets, I got the error:
400 Bad Request: malformed Host header'

I noticed that the host header sent by request was: `/var/run/docker.sock`

On the other hand, using curl it worked well, and the request looked like this:

```
$ curl -v --unix-socket /var/run/docker.sock http:/version
*   Trying /var/run/docker.sock...
* Connected to http (/var/run/docker.sock) port 80 (#0)
> GET /version HTTP/1.1
> Host: http
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Server: Docker/1.12.0 (linux)
< Date: Fri, 12 Aug 2016 13:14:44 GMT
< Content-Length: 198
```

And by overriding the host header, I also got request working:

``` js
request({url: 'http://unix:/var/run/docker.sock:/version', headers:{host: 'http'}}, function(err, response, body){...})
```

Could it be that request is not setting the host header correctly?

**Comment by mindnuts** [comment]
@manast I love you man (no homo)...i was facing the same issue and infact i opened a ticket on [Docker] (https://github.com/docker/docker/issues/26099)

Seems like the underlying implementation changed and it stopped working for me since Docker 1.12

**Comment by mindnuts** [comment]
@manast  BTW...to connect using Curl now you would have to use:
```bash
curl -v --unix-socket /var/run/docker.sock http://localhost/containers/json
```

**Comment by dfrankland** [comment]
If this helps anyone, I was able to get this to work with the built-in `http` module like below:
```js
const http = require('http');

const options = {
  socketPath: '/var/run/docker.sock',
  path: '/containers/json',
};

const callback = res => {
  console.log(`STATUS: ${res.statusCode}`);
  res.setEncoding('utf8');
  res.on('data', data => console.log(data));
  res.on('error', data => console.error(data));
};

const clientRequest = http.request(options, callback);
clientRequest.end();
```

**Comment by thonatos** [comment]
@dfrankland thanks. 

```
STATUS: 200
[ { Containers: -1,
    Created: 1483565663,
    Id: 'sha256:53df695896acdecb39a6914e25f7680011be26504dcb0675ac6e98c49379d171',
    Labels: {},
    ParentId: '',
    RepoDigests: [ 'redis@sha256:a06a61747e4a7b46788e2813b21ea6b06386df8e238e56f51f8793adb48f0a8b' ],
    RepoTags: [ 'redis:3.2-alpine' ],
    SharedSize: -1,
    Size: -1,
    VirtualSize: 19804367 } ]
```

**Comment by superbarne** [comment]
is there a solution for the request libary? I am facing the same problem..

**Comment by kovi** [comment]
I also had the 'host' issue and then another. Although it is not related to the malformed host, I wanted to mention it.

For me after the `host` header was added docker still said `Page not found`. The problem was that the request issued was `GET http:///var/run/docker.sock/v1.24/containers/json HTTP/1.1`

I have `http_proxy` env variables. I found that [`uri.path` is altered](https://github.com/request/request/blob/master/request.js#L399) when there is proxy set, even for unix sockets.
I got it working by setting `proxy: false`.

**Comment by manast** [comment]
if this fixed?

**Comment by prabhu** [comment]
This bug doesn't appear to be fixed yet. This bug in fact offers some indirect protection for certain cases like the one mentioned [here](https://github.com/nasa/openmct/issues/3391)

Attempting to exploit the open proxy vulnerability with the payload

```
curl "http://127.0.0.1:8080/proxyUrl?url=http://unix:/var/run/docker.sock:/images/json"
```

results in ```400 Bad Request: malformed Host header```

The moment this bug is fixed numerous applications could in fact become vulnerable.
