### ISSUE TITLE
Connection reuse with Forever

### ISSUE THREAD

**Issue by AlgoTrader** [request/request#236]
I am not sure this is bug or not yet. Let's call it an issue.

I use forever agent to send HTTPS POST requests. I failed to requse connections untill I did following

In the code:

foreverAgent.prototype.addRequest = function(req, host, port) {
  var name = host + ':' + port
  if (this.freeSockets[name] && this.freeSockets[name].length > 0 && !req.useChunkedEncodingByDefault) {
    var idleSocket = this.freeSockets[name].pop()

I inserted 
req.useChunkedEncodingByDefault = false;

Everything started to work exellent!
Unfortunately, setting content-length of post request does not fix the problem. Setting req.useChunkedEncodingByDefault = false; before req.end() does not help either.

Is there a way to reset useChunkedEncodingByDefault for POST requests without patching forever.js?

**Comment by vvo** [comment]
It's unfortunate that any POST request in Node 0.10 with request() module will never use keepalive. 0.12 seems ok (could not find the code path that triggers this good behavior)

For anyone wondering how to enable keepalive POST without forking the world:

```js
// horrible hack
var ForeverAgent = require('request/node_modules/forever-agent'); 

var savedAddRequest = ForeverAgent.prototype.addRequest;
ForeverAgent.prototype.addRequest = function(req/*, host, port*/) {
  req.useChunkedEncodingByDefault = false;
  savedAddRequest.apply(this, arguments);
};
```

YAY.

> the reason for leaving out things like PUT and POST was due to losing the data before a retry

1. When do we retry?
2. Retrying + Body is feasible if not .piped(), otherwise create a new connection

What do you think @mikeal?

**Comment by pangorgo** [comment]
Thanks @vvo  ! This saved me a lot of time, and seems to be only solution I found for running https with keep-alive on node 0.10.x
