### ISSUE TITLE
How to send two requests concurrently

### ISSUE THREAD

**Issue by vivekbrahmadandi** [request/request#2373]
In request module , how can we send two https requests concurrenly. Is it possible in this module or else we need to take the support of node js core things

**Comment by scotttrinh** [comment]
```js
var a = request(options);
var b = request(options);
```

Both requests are in-flight at the same time, since these functions (and most node functions in general) are asynchronous and non-blocking. If that satisfies what you mean by "concurrently", then there ya go! If you mean multi-threaded, you'll need to look at how Node does that through `child_process`es.
