### ISSUE TITLE
Calling GET to domain with .php in between seems to be returning 400 bad request

### ISSUE THREAD

**Issue by phoebs85** [request/request#2494]
I can call directly in my browser to a url like this:

https://[username]:[password]@api.bamboohr.com/api/gateway.php/visioncritical/v1/employees/changed?since=2016-12-20T23%3A46%3A53Z

This will return some results on screen.  However, when I call it using 
request.get([Same domain]);

This is always returning status 404.  I couldn't figure out why except suspecting it has something to do with the structure of the url (e.g say having .php in between)?   Is it possible that there is a defect in request module for not supporting url in such format?

**Comment by dege88** [comment]
Errorcodes on the bambooHR website indicate that 404 is for a not found resource:

https://www.bamboohr.com/api/documentation/
> 404 Not Found - The resource was not found with the given identifier. Either the URL given is not a valid API, or the ID of the object specified in the request is invalid.

Maybe you're using the api wrongly?
looking in https://www.bamboohr.com/api/documentation/changes.php
seems like you're missing a **/** after changed:
`https://[username]:[password]@api.bamboohr.com/api/gateway.php/visioncritical/v1/employees/changed/?since=2016-12-20T23%3A46%3A53Z`

Also consider to use an already made package to inteface with the api:
https://github.com/tresni/node-bamboohr

**Comment by phoebs85** [comment]
Thank you so much for the quick response!
I tried adding the '/' after 'changed' but still getting 400 Bad request.   

I will take a look at the node-bamboohr package and see if that helps.

**Comment by debone** [comment]
I'm having the same 400 Bad request issue with BambooHR also, but on browser is working.

Could you solve this @phoebs85 ?

**Comment by phoebs85** [comment]
Hi @debone:

Sorry for the late response, but I did get it to work by using the npm 'request' library.   I didn't call the URL with the password / key, but instead I did it like this:
````
const callUrl = 'https://api.bamboohr.com/api/gateway.php/' + this.subDomain + path;
const auth = 'Basic ' + new Buffer(username + ':' + password).toString('base64');
var args = {
      method: method,
      url: callUrl,
      headers: {
        Authorization: auth,
        Host: 'api.bamboohr.com'
      }
    };

request(args, function(err, response, body) {
 ...
}
````

This worked for me.

**Comment by debone** [comment]
Oh, tested here and the `Host: 'api.bamboohr.com'` is actually the key to make it work 👍

Thanks @phoebs85
