### ISSUE TITLE
How to use dnscache with request?

### ISSUE THREAD

**Issue by jdarling** [request/request#2536]
I've read through everything I can find in the backlog of issues and don't see a reference to how to do dns caching instead of resolving dns every time.  There are modules already out that do the dns lookup caching already, but I can't figure out how to make request use them.

Specifically we are seeing random dns.lookup calls that can take seconds due to network latency.  Ideally would like to put something in front of requests call to dns.lookup and have it provide the cached result if/when slowdown occur.

Any ideas?

**Comment by voidmonk** [comment]
You'll have to install a DNS caching server like dnsmasq, powerdns, unbound etc., and change `/etc/resolv.conf` to point to the DNS server IP.

**Comment by Ry7n** [comment]
I just did so local fiddling to verify, and it looks like since [yahoo/dnscache](https://github.com/yahoo/dnscache) modifies the global DNS module, using it anywhere in your node app _should_ work across all of your HTTP requests, including those done via `requestjs`.

So the answer is probably as simple as just adding this anywhere in your app:

```
require('dnscache')({ enable: true });
```

...should be all it takes.

**Comment by himharsh1997** [comment]
> I just did so local fiddling to verify, and it looks like since [yahoo/dnscache](https://github.com/yahoo/dnscache) modifies the global DNS module, using it anywhere in your node app _should_ work across all of your HTTP requests, including those done via `requestjs`.
> 
> So the answer is probably as simple as just adding this anywhere in your app:
> 
> ```
> require('dnscache')({ enable: true });
> ```
> 
> ...should be all it takes.

This help me getting resolve ENOTFOUND for 618 request.
