### ISSUE TITLE
Cant find module/var/task/index?

### ISSUE THREAD

**Issue by nmwalkers** [request/request#2596]
Tried literally downloading this and put onto lambda and i get this error when trying to test the function: 
{
  "errorMessage": "Cannot find module '/var/task/index'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}

**Comment by rahulgaikwadsipl** [comment]
I got the same error , and after changing my functions file name to index.js ,
its works fine for me.

**Comment by cristal2431** [comment]
I am still getting the same error. My file name is same as mentioned above.

**Comment by kritikaMadhwani** [comment]
@cristal2431   please ensure you have All the three files,
node_modules
index.js
packaje.json

secondly , please check whether the node_modules have packages.. because i was using other folder that is having readme files...

third , check u are zipping the content of the folder i.e selecting all the three and zipping into one file..
and not zipping the folder.

this is works fine for me.
