### ISSUE TITLE
TypeError: Failed to Fetch

### ISSUE THREAD

**Issue by chandrasekarb** [request/request#2611]
Can't get response on jsx file (Reactjs ES6),  while using the following.

```js
import request from 'request';
/********/
  const url1 = 'http://www.google.com'
  const options = { method: 'GET', url: url1 };
  request(options, (error, response, body) => {
  if (error) alert(error);
  alert(JSON.stringify(body));
  });
/******/
```

### Output:
TypeError: Failed to Fetch

Any one please give me a solution to resolve the above error.
Thanks.

**Comment by robeerob** [comment]
Works for me with Node.js (did not try to replicate with React).

I might be wrong, but since Request is a node module, you can not just import it in your React project and expect it to run like that. Maybe something like this could be helpful for you:
[Browser Request](https://www.npmjs.com/package/browser-request)
