### ISSUE TITLE
request module should follow SemVer - breaking change in 2.76

### ISSUE THREAD

**Issue by koresar** [request/request#2621]
### Summary
The release v2.75 declared that the `request` is gonna stop supporting node.js v0.10. This should have been released as v3 instead of v2.75. Why?
Because the next release v2.76 introduced [the breaking change](https://github.com/request/request/pull/2431/files#diff-ccc0734f65dd7a299409ff07d35be095R742) which breaks in node.js v0.10

Our applications' dependencies in package.json:
`    "request": "^2.58.0",`
Meaning, that npm will install any `request` module which starts with `2.`.

Suddenly, servers started to fall over when a remote host becomes unavailable...

### Simplest Example to Reproduce
* node.js v0.10 (UPD: **any** node.js version)
* `npm i nock request`
```js
const assert = require('assert');
const request = require('request');
const nock = require('nock');

nock('http://localhost:8080').get("/").delayConnection(1000).reply(200);
request({url: 'http://localhost:8080/', timeout: 10}, function (err) {
    assert.ok(err);
    assert.equal(err.code, 'ETIMEDOUT');
});
```

### Expected Behavior
The code does not error. Exit code is 0.
This is confirmed on versions <=2.75

### Current Behavior
Since v2.76 and forward the test fails.
```

AssertionError: null == true
    at Request._callback (/Users/koresar/code/client/tmp.js:7:12)
    at Request.self.callback (/Users/koresar/code/client/node_modules/request/request.js:186:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/koresar/code/client/node_modules/request/request.js:1060:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/Users/koresar/code/client/node_modules/request/request.js:980:12)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)
```

### Possible Solution
Re-release as v3. Start strictly following SemVer.
Implement the `timeout` feature back (only for <=0.10 node.js environments).

### Your Environment
OS X Sierra

**Comment by koresar** [comment]
Update to the info above.
I was wrong. The issue is not only node.js 0.10 related. It's all versions (v4, v6).

**Comment by dantman** [comment]
Real world effect of this violation of semver:
https://github.com/node-facebook/facebook-node-sdk/issues/118

Old packages that depend on 0.10 supporting versions of request like `request@^2.67.0` are broken because the latest version includes the breaking change of updating the minimum version and depends versions of other packages that explicitly do not support 0.10 and include syntax that does not work before node 4.

This is entirely `request`'s fault because these other libraries are properly following semver, they incremented their major version numbers when they dropped support for `0.10`. While `request` just started depending on the new major release with breaking changes that affect request without bothering to increment its own major version number.

**Comment by dantman** [comment]
Other relevant issue on this package: #2772.

**Comment by mikeal** [comment]
Closing as duplicate.

**Comment by koresar** [comment]
@mikeal it sounds like a duplicate, although the change broke it for **all** node.js versions.
This is different from the #2772 imo
