### ISSUE TITLE
Callback never called when file stream fails in formData

### ISSUE THREAD

**Issue by esatterwhite** [request/request#2695]
### Summary

When sending multipart data via `formData`, if there is request stream that errors, the request is never made, and the callback is never executed. There is no indication of what happened

### Simplest Example to Reproduce

```js
const fileStream = request.get('http://doesnt.exist/file.test.png')
  .once('error', (err) => {
     console.error('Attachment failed to download')
  })
request({
  method: 'POST'
, uri: `http://localhost:3000`
, json: true
, formData: {
    from: 'test@test.com'
  , to: 'customername@test.com'
  , subject: 'test attachments'
  , html: '<p>hello <strong>world</strong> <img src="cid:test.png" /></p>'
  , inline: [
      {
        value: fileStream
      , options: {
          filename: 'test.png'
        , contentType: 'image/png'
        }
      }
    ]
  }
}, (err, res, body) => {
  console.log('never called')
  if (err) return console.error(err)
  console.log(res.statusCode, body)
})

```

### Expected Behavior
The request should be made, with out the failed attachments, or the callback should executed with some indication of what happened.

### Current Behavior
If the attachment stream encounters a net work error (`ECONNREFUSED` - the url doesn't exist). the request is never actually made, and/or the callback is never executed indicating that there was a problem with the request. This works ok if the server returns an error code (500).

### Context
We are trying to send multi-part email messages with attachment file. We are creating an array of request streams in the `formData` objects. We get the error events for the streams when they fail, but the actual request callback is never called. More importantly, the request is never actually made

| software         | version
| ---------------- | -------
| request          | 2.73.0
| node             | 6.10.0
| npm              | 3.10.3
| Operating System | Arch / Debian jessie

**Comment by renby** [comment]
Your error is because there isn't actually anything listening to errors on the FormData object. FormData.prototype.on is not a function on either the native implementation of FormData, or in the node module form-data. 

There appears to be a general issue with FormData in the code, because it doesn't look like it's pulling in the form-data package if there is a native implementation of FormData already. My browser console is throwing undefined errors even on functions that are definitely defined in form-data (e.g. `.getHeaders()`, `.getLength()`)

item | version
-- | --
request | 2.83.0
node | 6.9.2
npm | 3.10.9
Browser | Chrome 60 for Mac
