### ISSUE TITLE
Release @2.82.0 broke semver minor version

### ISSUE THREAD

**Issue by louisbuchbinder** [request/request#2772]
Hi sorry to be a pain, but upgrading the Hawk dep broke the semver minor version. This is a breaking change as the new hoek uses const instead of var. Hawk uses Hoek, which uses `const`. This release should be major version @3.

```
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
```

**Comment by rogers140** [comment]
Same here. Node version: 0.12.7 for historical reason.

**Comment by louisbuchbinder** [comment]
tell me about it...

**Comment by rahul2983** [comment]
I am having a similar issue. Using node version `0.12.7` Please revert back to request version `2.81.0` or change the hawk dependency to version `~3.1.3`

**Comment by trevoro** [comment]
Same here

**Comment by boJackEden** [comment]
Same issue. Breaking my build. @rahul2983 quick update would save me a lot of hassle.

**Comment by rogers140** [comment]
We are using another module that depends on this, and in that module, it writes dependencies as `request ^2.54.0`. Things really beyond my control now... either we make our local copy of that module or just upgrade node (highly leverage here)

**Comment by dbine** [comment]
+1 same issue.  Please resolve per everyone's suggestions above.

**Comment by allardvanderouw** [comment]
I had the same problem, temporarily fixed it by changing my dependency from `"request": "^2.81.0"` to `"request": "2.81.0"`...

**Comment by googlegovind** [comment]
same here!

**Comment by impol** [comment]
npm-shrinkwrap.json
```
{
 dependencies: {
  request: {
   version: "2.81.0"
  }
 }
}
```

**Comment by gogson** [comment]
Lesson here is always fix your package versions, don't rely on people and semantic versioning myth.

**Comment by danielnitu** [comment]
Changed from "^2.78.00" to "2.78.00". Our server was just sending a 502 error. I agree with @gogson, fix your versions, don't rely on others.

**Comment by peterlundberg** [comment]
This broke our builds too as the new version of hawk uses `let` etc in its source which is  as expected by node < 6 but also uglify used in many build pipes to minimize distributions. So while unintended this is a big surprise for many users of the library. At a minimum also `engines` in package.json should get updated. Unless the new version is very warranted reverting to a version of hawk that does not require new runtimes would be a good idea.

**Comment by kshay** [comment]
Our build broke yesterday too due to upstream node-sass, jsdom, and probably others. We're working on workarounds now but it would be great if this could be reverted/fixed in this package.

**Comment by watson** [comment]
Hopefully this can all teach us a lesson for the future: Any project that stops testing against a major version of Node.js should consider it a breaking change. Else you don't know if you by accident introduce breaking changes down the line. Then this issue would not have happened 😄

This project used to test both [v0.10](https://github.com/request/request/commit/5eeafa25097d42d6e2588122158761187d27e6ce#diff-354f30a63fb0907d4ad57269548329e3) and [v0.12](https://github.com/request/request/commit/4c4557faabf415a01ce2d8a7c3473311c126f69b#diff-354f30a63fb0907d4ad57269548329e3) in the `.travis.yml` file.

**Comment by mikeal** [comment]
The solution to your problems is quite simple: **STOP SUPPORTING v0.10 & v0.12.**

Almost a year ago the Node.js project's maintenance window ended for pre v4 releases. This includes critical security updates and OpenSSL. **It is irresponsible to continue to support and encourage people to run these versions of Node.js.**

Bumping the major version would require every downstream user of request, which if you include deep dependencies is more than half the registry, to manually bump their major version in order to continue getting new releases of Node.js.

It's not fair to the people who are doing the right thing and keeping up to date with supported versions of Node.js to opt them out of updates without intervention so that people who are refusing to upgrade can continue to get fixes.

If you **MUST** support v0.10 and v0.12 then **you** can lock your package version while the rest of the ecosystem continues to get fixes, including security fixes like the ones in hawk.

It's quite simple, if you are running an old and insecure version of Node.js then you are no longer going to get security fixes from Node.js **OR** request, and its dependencies like hawk.

**Comment by mikeal** [comment]
BTW, these "breaks" all seem to be in tests on v0.10 and v0.12. 

Remove travis support for those releases. They are unsupported by the Node.js project, they shouldn't be supported by your package.

**Comment by xepps** [comment]
Whilst I agree that no one should be on an old version of node - that option is not always available. 

Traditionally, if you want to drop support for something and introduce a breaking change, the way to do it is with a major version.

**Comment by mikeal** [comment]
> Whilst I agree that no one should be on an old version of node - that option is not always available.

Nobody is saying you *have* to upgrade to a new Node.js. Go ahead and run whatever you want forever.

But, you don't **ALSO** get dependency upgrades in perpetuity. If you want to run an old applications on an old Node.js, lock your deps. Otherwise they are likely to break.

**Comment by mikeal** [comment]
> Traditionally, if you want to drop support for something and introduce a breaking change, the way to do it is with a major version.

I just don't consider a change "breaking" if it breaks on an unsupported version of Node.js.

**Comment by lxe** [comment]
> The solution to your problems is quite simple: STOP SUPPORTING v0.10 & v0.12.

It's the correct solution, no doubt about it, but it's far from being "quite simple" for reasons related to scale, organizational makeup, technical debt, prioritization of work, separation of organizational concerns, etc...

**Comment by mikeal** [comment]
> It's the correct solution, no doubt about it, but it's far from being "quite simple" for reasons related to scale, organizational makeup, technical debt, prioritization of work, separation of organizational concerns, etc...

I think we're conflating application upgrades and module upgrades.

Module can just drop old versions from their travis.yml file. That's pretty easy.

Applications are much harder, but if they decide not to upgrade they can simply lock down the versions of their deps and stop upgrading their deps.

**Comment by lxe** [comment]
> Applications are much harder, but if they decide not to upgrade they can simply lock down the versions of their deps and stop upgrading their deps.

That's true, but then the application won't receive speedy security updates and bug fixes. It's a bit of a balance...

I completely agree though that supporting legacy Node versions from a package maintainer's perspective is very difficult, and advising both the module and application maintainers to drop support for legacy Node versions is good advice.

**Comment by rogers140** [comment]
@mikeal I really think @xepps made the correct point. The issue becomes too hard to solve if old project is depending on some modules that are using some other modules that are using `request`. For example: `googleapis` -> `gapitoken` -> `request ^2.54.0`, in this case, if a project is using `googleapis` in node 0.12.7, they are screwed and there is no easy way to fix this, other than upgrading node (not always an option). So making this change in a major version like 3.0.0 or something like that would help a lot and resolve it.

**Comment by esphen** [comment]
Please consider that version numbers are free, customers experiencing bugs in production is expensive. This caused me 1.5 hours of fumbling while prod was on fire. No one is going to care that your library is v15.0.0 if it means that dropping backward compat is done responsibly (with a semver major version). 

I totally understand the position that 0.x is to be universally dropped, but that isn't done overnight. In my opinion the only responsible thing to do, **especially** when you have a large number of downstream projects, is to make dropping 0.x compat a major version regardless of 0.x's support state. 

Even if one does not share this view, others will, and they deserve to be warned of the potential breaking changes in their library with the red flag of a major version.

**Comment by mikeal** [comment]
> Please consider that version numbers are free

Except when you have a large install base that only automatically upgrades minor releases. If we push a new major it would take years for maybe 10% of our users to be getting the number of updates they get now.

**Comment by hueniverse** [comment]
This is a case of who do you want to optimize the experience for: people who run on unsupported platforms or people who keep up with the bare minimum of staying on a supported node LTS version? I completely agree with @mikeal that the people we should care about more are those running supported versions.

The actual semver violation was 11 months ago here: https://github.com/request/request/commit/01aefdd87cdd9cc44af6828c55fe5ef9c7e205d7

Dropping support should have been a major then when the contract changed. The same argument could have been made then though, but back then I would have been more supportive of those losing compatibility. A year later, now that request v2 has been re-contracted as node 4+, it's too late to make this argument for a major bump.

Also - doesn't npm complain when you install request on unsupported node version?!

<rant>
The module system is never a valid excuse for you to have poor understanding of your full stack dependencies. I am tired of people making the argument that they should be able to just use whatever random module from the npm registry they find and things should magically work. It's software made by humans. I review every single dependency of code I bring into my projects and all their dependencies. And I expect everyone to do the same. Sounds unrealistic? Maybe use a lot less imported crap that you probably don't need. Go lookup some of my old rants about tiny modules...

If your production environment was affect by this, you have a shit production setup. Period. You clearly don't know how to run node in a responsible manner. If you are still running node 0.x you are in completely uncharted territory - you are running unsupported garbage that is known to have bugs and security issues. At least this time the issue was clear and your shit environment stopped working. But you are as likely to hit really complex bugs in socket handling and memory leaks that a "semver compliant" version of request can expose that only exists in node 0.x.

If you are running an unsupported version of anything, you should stop upgrading everything! Own your mistakes for a change.
</rant>

**Comment by mikeal** [comment]
> Also - doesn't npm complain when you install request on unsupported node version?!

Yup :)

**Comment by esphen** [comment]
In reply to @hueniverse 

>  I completely agree with mikeal that the people we should care about more are those running supported versions

Yes, however there was a time when node 0.x was supported. My argument is that at the point you chose to no longer support it, there should have been a major version increment. If there had been, then this never would have happened. Like you mention, that was 01aefdd.

> If your production environment was affect by this, you have a shit production setup. Period. You clearly don't know how to run node in a responsible manner.

Please don't make assumptions about people you don't know's competency or intentions, it degrades the discussion. Mistakes happen regardless of competency. I'll happily own up to the fact that there should have been lockfiles on the legacy repos if you own up to the fact that changing the node version in 01aefdd should have been a major version.

Since the major version was not correctly incremented in 01aefdd, you can make the argument for or against this version requiring a major version, but I don't want to get into that. Both are valid.

**Comment by hueniverse** [comment]
Another way to look at this for anyone who got hit by this: your environment is fully exposed to the worse kind of DoS attack vector - operational incompetence.

I am being harsh here for a reason because you got lucky today and some of you still consider this to be someone else' fault. This change caused your application to fail instead of leak data, lose money, or cause irreversible hard. What I hope you have learned today is that ANYONE with publish rights to ANY module you depends on, directly or indirectly, can shut down your entire environment. That is at best fucking ridiculous and at worst criminally negligent.

Think about what you are admitting to have created - an environment where hundreds (if not thousands) or people have the power, maliciously or innocently, to put you out of business (if only for a short period of time), without any accountability or recourse. Maybe open source isn't for you.

Most of you don't know me, don't give a crap about what I do, and certainly don't consider me to be an active security threat. And yet, I have publish rights to modules that are being downloaded by pretty much every fucking node deployment in the world. I have at least 95% access. I have publish rights to `qs` and I don't even maintain that module anymore - that's 2.5 million **daily** downloads. npm Inc. will stop me from deleting the module from the registry, a minor improvement over the last registry clusterfuck. But I can still push garbage and impact 2.5 million clients if it takes npm Inc a full day to shut me down.

There is always a delicate balance between productivity (using loose version requirements in your package file to automatically get new version) and security (not getting hit by random shit being posted to the registry). But an easy line to draw is between your local development environment and your production or operational environments.

"Can I afford this system to go down or be exposed to malicious code for a short period of time?" is a simple question to ask yourself. For your personal laptop? probably. For the team's build servers? probably not. For your production system? fuck no!

If anyone can cause you to run whatever code they want, you have a massive problem. Again, I can publish **right now**, a version of `qs`, that when loaded into memory, will upload files from your machines to my cloud account. Maybe I'll grab your browser history and publish some interesting stats on the kind of porn node developers prefer... It won't last long as people will notice and npm Inc. will take action. But for a brief time, I will fucking p0wned your environment.

And no, you can't event trust me because my systems can be hacked. If someone gets access to an npm access token from any of my machines, they gain the same power... I don't even trust modules I am the sole publisher of.

Consider this experience an inexpensive lesson in open source operational security.

**Comment by mikeal** [comment]
> Yes, however there was a time when node 0.x was supported. My argument is that at the point you chose to no longer support it, there should have been a major version increment.

This has actually never been the case. We dropped support for 0.1.x, 0.2.x, 0.4.x, 0.6.x and 0.8.x without a semver major, and those releases were all major releases (Node.js didn't follow semver until iojs). The only semver major we did was for breaks in request's API.

**Comment by jasonpincin** [comment]
> Except when you have a large install base that only automatically upgrades minor releases. If we push a new major it would take years for maybe 10% of our users to be getting the number of updates they get now.

Does anyone actually auto-upgrade any dependency anymore? Just further exasperates this entire problem.

**Comment by mikeal** [comment]
@jasonpincin If nobody was auto-upgrading deps we wouldn't have people in this issue saying this version broke their 0.12 setup :)

**Comment by jasonpincin** [comment]
Fair. :)

**Comment by eandersonpgi** [comment]
> Except when you have a large install base that only automatically upgrades minor releases. If we push a new major it would take years for maybe 10% of our users to be getting the number of updates they get now.

> If nobody was auto-upgrading deps we wouldn't have people in this issue saying this version broke their 0.12 setup :)

I don't think you can have it both ways.

**Comment by ggarciao** [comment]
This thread depict how wrong is the notion of semantic version in practice:

@mikeal considers that the change is not a MAJOR one because it breaks unsupported (but not unused) nodejs releases.

This decision complies with the semantic version definition ? Yes ? No ? It seems to me that is up to the dependency provider ... and that is something that you cannot rely on 'automatically' (e.g. using the '^' operator in npm). 

And if you cannot rely on that ... what is the real value of semantic versioning ? ( Place your witty answer here )

**Comment by jasonpincin** [comment]
> I don't think you can have it both ways.
> This thread depict how wrong is the notion of semantic version in practice:

Agree with you both. It's why I pin versions & commit npm-lock/shrinkwrap in my apps, and advocate that others do the same. In the past I've not pinned versions in my published modules. That was a mistake.

**Comment by dantman** [comment]
I'd like to chime in not as a someone with a crap setup using an old version of node, but as a package author.

One of my packages depends on request, I use a `request@^` dependency in my package (instead of `~`) to ensure that my package will not be locked to an old minor version of request that will no longer get security updates and will instead use the most recent version of `request` that is still supposed to be compatible with my package. If `request` made a major version increment to drop support for an upstream EOL version of node, I would be happy to do the same in my package while updating the nodejs compatibility version in my package as well.

However, because back in `2.77.0` `request` decided to publish the breaking change of dropping 0.10 support, old versions of **my** package that explicitly state a contract of `"node": ">=0.10.0"` are now broken in a version of node that they state they support. So that version contract in that major version of my package is now broken, because of `request`.

Now, because `request` refuses to honor its own contract in a way that can affect my package, I've actually started considering pinning my package to `request@~` instead of `request@^` to ensure that `request` never again causes that contract in my package to break in current/future releases of my package.

Which is of course the complete opposite result of the `request` authors' reason for not incrementing the major. The desire to keep the same major version number despite making technically breaking changes just so packages targeting that major version still get security updates on the "currently supported" versions of node. May cause the opposite effect if packages instead start pinning `request` to `~` which won't get security updates.

And as for the "0.10 is EOL, shouldn't be used because it doesn't get security upgrades, and thus we can make breaking changes without having to increment our major version number" argument, that argument is faulty, it completely ignores linux support. node@0.10.29 is still packaged with the debain release "jessie", jessie is a LTS release that will receive security upgrades till April 2020, and historically Debian has a habit of applying major security patches to packages to fix security bugs even when the original software considers these versions EOL and isn't applying security patches to them. This means that for users of debian jessie, node@0.10 should still be a reasonable version of node to use until April 2020.

**Comment by mikeal** [comment]
Debian has a completely insane and outdated notion of what is secure/stable. Node.js 0.10 is **not** secure and it is **not** stable. Period. Full stop. There is no definition of the term "secure" or "stable" that applies to 0.10.x. I'm not going to try and understand the internal logic of Debian maintainers but I'm also not going to consider their mindset in decisions I make in this project.

@dantman correctly notes that 2.77.x is when we deprecated 0.10.0 (and 0.12.0 btw).

We noted this by changing the target range in package.json. There's a reason that the supported versions of Node.js are independent of the semantic version of request itself. Anyone run old versions from that point on would see large warnings from npm on installation.

I've said this several times, and I'll say it again, I'm not going to silently opt the majority of request users out of security updates by bumping the major version in order to *not* inconvenience people running EOL versions of Node.js.

Everything is a tradeoff. I understand that people stuck on old versions don't like this tradeoff, but you are in the minority, and we only have the resources to support a single major line of development, so the choice was between breaking you or opting the rest of the community out of automatic updates. This will not be the last time you are inconvenienced by changes like this in dependencies so it's a good idea for you to lock down your deps with shrinkwrap and stop updating them. Or, better yet, update to a supported version of Node.js.

For package authors: it's up to you whether or not to bump the major version, but supporting EOL versions of Node.js is not a good practice and encourages irresponsible/insecure behavior of your users.

For a longer rant on the reality of Security and Sustainability in open source you can read this https://twitter.com/mikeal/status/911353245628481536

**Comment by dantman** [comment]
> I've said this several times, and I'll say it again, I'm not going to silently opt the majority of request users out of security updates by bumping the major version in order to not inconvenience people running EOL versions of Node.js.

Installation of older/insecure versions of a library without security updates is not silent. Not if you bother to [`deprecate`](https://docs.npmjs.com/cli/deprecate) them.
```shell
npm deprecate request@^2 "request 2.x releases no longer receive security updates, please upgrade to request 3.x"
```

> Debian has a completely insane and outdated notion of what is secure/stable. Node.js 0.10 is not secure and it is not stable. Period. Full stop. There is no definition of the term "secure" or "stable" that applies to 0.10.x. I'm not going to try and understand the internal logic of Debian maintainers but I'm also not going to consider their mindset in decisions I make in this project.

You don't seem to understand how Debian LTS works. Debian applies security patches to software in its packages, even if they are not applied to the upstream version. Would you care to actually list an example of a security issue in nodejs@0.10 that still affects jessie? I can find an example of the opposite.

For instance, node.js is affected by the [CVE-2017-1000381](https://c-ares.haxx.se/adv_20170620.html) security issue discovered this year in `c-ares` which the official versions of node.js have only patched 4+ with fixes for (fixed in `4.8.4`, `6.11.1`, `7.10.1`, `8.1.4`. However, the `c-ares` version used by the nodejs@0.10 package included in Debian jessie, [has been patched with the CVE-2017-1000381 fix](http://metadata.ftp-master.debian.org/changelogs/main/c/c-ares/c-ares_1.10.0-2+deb8u2_changelog). So despite the official node.js release of 0.10 being vulnerable to CVE-2017-1000381, the Debian jessie release of 0.10 is **not** vulnerable to that security issue.

----

And you don't seem to be guaranteeing that I won't one day wake up one day in 2018 and find that a release of my package is now broken in node@4 because of a `request@^` dependency despite the fact that nodejs@4 will still likely be present in whatever the current stable version of Debian is (`stretch` is the current release and has `4.8.2~dfsg-1`, `buster` is the current testing, i.e. upcoming release, and has `4.8.4~dfsg-1`), Debian will be keeping it updated with security patches, and the broken version of my package declares that it supports node `>=4` and is "the" latest version of the packages users on that version of node can install.

**Comment by mikeal** [comment]
> Installation of older/insecure versions of a library without security updates is not silent. Not if you bother to deprecate them.

If people paid attention to these warnings then we would have all these people so surprised by the latest release. They've been easily ignoring version conflict warnings for almost a year.

> You don't seem to understand how Debian LTS works. Debian applies security patches to software in its packages, even if they are not applied to the upstream version. Would you care to actually list an example of a security issue in nodejs@0.10 that still affects jessie? I can find an example of the opposite.

To my knowledge, Debian has **never** back ported a single fix to an old versions of Node.js, much less all the dependencies an application might have.

Perhaps they do this privately and people paying the right vendors are getting fixes. If they are, fine, they can patch request and the deps we're taking in request along with their Node.js work.

**Comment by mikeal** [comment]
> And you don't seem to be guaranteeing that I won't one day wake up one day in 2018 and find that a release of my package is now broken.

Not exactly. If you keep using the same version of `request` you will never break.

If you are not locking the version of `request` and continue trying to update it, yes, a new release will eventually break.

Other packages will also break as old releases continue to fall out of circulation and are not tested against. This is a good thing, we all need to move forward and stay on support and secure versions of Node.js.

**Comment by dantman** [comment]
> To my knowledge, Debian has never back ported a single fix to an old versions of Node.js, much less all the dependencies an application might have.

I just gave an example of Debian backporting a fix to a security vulnerability that affects node. Debian splits up packages, i.e: the libraries nodejs uses (the biggest source of security issues) are separate packages instead of directly part of the nodejs package and they get security packages individually, which implicitly fixes the security issue in node. So the only time Debian needs to make a backport directly to the nodejs package that you'll see in the changelog for the nodejs package is if it's a security vulnerability directly in the nodejs source code created by one of the nodejs devs (a rare type). Would you care to give me an example of one of those, or another security vulnerability you'd like me to check the nodejs package for?

**Comment by mikeal** [comment]
Great! Debian can do the work of backporting hawk to 0.10.0 and keeping a working fork of request for 0.10.x users, cause I'm not going to waste my time supporting EOL versions of Node.js. 

If they want to support EOL software they can do all the work of supporting it, both in Node.js and in dependencies like `request`.

**Comment by jasonpincin** [comment]
So to summarize what's come out of this: Pin everything. Semver (within NPM at least) has an extremely finite window in which it has any meaning at all.

**Comment by dantman** [comment]
> So to summarize what's come out of this: Pin everything. Semver (within NPM at least) has an extremely finite window in which it has any meaning at all.

shrinkwrap/yarn is good to use in applications, it'll give you control over exactly what versions of libraries are installed and only upgrade them when you intend to upgrade packages.

However I wouldn't say that about semver or npm. The mass majority of packages used by people on npm stick to semver. For example the `hawk` package `request` uses where this error originally is thrown from [bumped its major to 4.0.0](https://github.com/hueniverse/hawk/commit/e01118175b65e7e0fdf1afbe688ca8478a9808c5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) when it dropped support for nodejs@<4. It's just that `request` is one of the few packages that doesn't care to stick to semver when doing so. The only reason that hawk is throwing that error is because `request` started depending on it without a major release. So you can safely use `^` for most packages, but do have to be wary of a few black sheep like `request`.

**Comment by travi** [comment]
i think a better summary might be to not use dependencies that are marked as incompatible. even locking dependencies isn't ideal if you aren't first confirming compatibility. 

for example, my builds call `npm ls` and check the status code to ensure things like peer-dependencies are compatible with each other. i do this even before i run my test suite to ensure i have a reasonable starting point.

i'm not sure if that particular command would fail for packages that are incompatible with the current node version (it does not fail for deprecations), but i would be surprised if there weren't a way to ensure that your project is not ignoring warning programmatically. 

can anyone confirm if `npm ls` or a similar command could help identify node version compatibility so that others running into issues could take real action to improve their situation, even if upgrading isn't an option?

**Comment by jokeyrhyme** [comment]
Sometimes users just forget to update their Node.js, so I built these:

-   https://github.com/jokeyrhyme/update-nodejs-notifier.js
-   https://github.com/jokeyrhyme/package-engines-notifier.js

In my own CLI tools, I usually have these set to start bugging users if their version of Node.js is older than 90 days, and if their Node.js version doesn't match package.json:engines.node

**Comment by hueniverse** [comment]
This will get even more fun next week when I publish new major versions of all my modules to only support node v8... :-)

**Comment by Laxmantln** [comment]
# Below error/issue resolved with this solution:

### Solution:
**sed -i '27 a "request":"2.81.0",' /opt/apache-ambari-2.2.2-src/ambari-web/package.json**

I just added specified "request" version(older version "2.81.0")  in "package.json" file below problem resolved. 

### _Here is my error:_
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (compile-brunch) @ ambari-web ---
[DEBUG] Configuring mojo org.codehaus.mojo:exec-maven-plugin:1.2.1:exec from plugin realm ClassRealm[plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'org.codehaus.mojo:exec-maven-plugin:1.2.1:exec' with basic configurator -->
[DEBUG]   (f) basedir = /opt/apache-ambari-2.2.2-src/ambari-web
[DEBUG]   (f) classpathScope = runtime
[DEBUG]   (f) commandlineArgs =  build
[DEBUG]   (f) executable = brunch
[DEBUG]   (f) longClasspath = false
[DEBUG]   (f) project = MavenProject: org.apache.ambari:ambari-web:2.2.2.0.0 @ /opt/apache-ambari-2.2.2-src/ambari-web/pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@5ce4369b
[DEBUG]   (f) skip = false
[DEBUG]   (f) workingDirectory = /opt/apache-ambari-2.2.2-src/ambari-web
[DEBUG] -- end configuration --
[DEBUG] Executing command line: brunch build

/opt/apache-ambari-2.2.2-src/ambari-web/node_modules/ember-precompiler-brunch/node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
Error: You probably need to execute `npm install` to install brunch plugins. SyntaxError: Use of const in strict mode.
  at /opt/node-v0.10.44-linux-x64/lib/node_modules/brunch/lib/watch.js:433:19
  at Array.map (native)
  at loadDeps (/opt/node-v0.10.44-linux-x64/lib/node_modules/brunch/lib/watch.js:418:10)
  at loadPackages (/opt/node-v0.10.44-linux-x64/lib/node_modules/brunch/lib/watch.js:438:15)
  at /opt/node-v0.10.44-linux-x64/lib/node_modules/brunch/lib/watch.js:458:19
  at /opt/node-v0.10.44-linux-x64/lib/node_modules/brunch/lib/helpers.js:529:16
  at /opt/node-v0.10.44-linux-x64/lib/node_modules/brunch/lib/helpers.js:485:14
  at /opt/node-v0.10.44-linux-x64/lib/node_modules/brunch/node_modules/read-components/index.js:263:16
  at /opt/node-v0.10.44-linux-x64/lib/node_modules/brunch/node_modules/read-components/index.js:72:14
  at Object.cb [as oncomplete] (fs.js:169:19)

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Ambari Main ........................................ SUCCESS [  3.970 s]
[INFO] Apache Ambari Project POM .......................... SUCCESS [  0.591 s]
[INFO] Ambari Web ......................................... FAILURE [01:08 min]

**Comment by jsumners** [comment]
I'm late to the party, and I can't resist chiming in.

Everyone who is complaining about "semver not being adhered to", try reading the spec again. The spec deals specifically with **the public API** of the versioned item. How that API is implemented is not covered, as long as that API remains the same:

> 5. Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

http://semver.org/#spec-item-5

In fact, it's point number 1 in the summary of the spec.

Did `request`'s API change? No? Then semver wasn't broken.

**Comment by koresar** [comment]
I asked other people what do they think of `request` package versioning strategy.

There are only 10 responses. Please, do the same poll and you'll get the similar result.

![image](https://user-images.githubusercontent.com/1622575/40403815-9d74a400-5e97-11e8-83f6-ed8b93eb0d79.png)

My point is - it does not matter what is the most SemVer spec compliant way of versioning. People expect NPM modules to bump major version when they drop support of an old node.js.
