### ISSUE TITLE
Emit 'finish' event on writable streams

### ISSUE THREAD

**Issue by ad-si** [request/request#2905]
### Summary

According to the [documentation](https://nodejs.org/dist/latest-v9.x/docs/api/stream.html#stream_events_finish_and_end) readable streams emit 'end' and writable streams emit 'finish'.
However, `request` seems to always emit 'end'.

### Simplest Example to Reproduce

```js
const fs = require('fs')
const path = require('path')
const request = require('request')


const postReq = request({
    method: 'POST',
    uri: 'http://devnull-as-a-service.com/dev/null',
  })

postReq.on('finish', () => console.log('This should be called!'))

fs
  .createReadStream(path.join(__dirname, 'index.js'))
  .pipe(postReq)
```

### Expected Behavior

Outputs `This should be called!`

### Current Behavior

Does nothing

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.85.0
| node             | 9.10.1
| Operating System | macOS

**Comment by ttulka** [comment]
I think this is what you are looking for:
```
postReq.on('end', () => console.log('This should be called!'))
```

**Comment by ad-si** [comment]
Like I said, that's wrong! Readable streams must emit 'end' and writable streams must emit 'finish'!

**Comment by ttulka** [comment]
Well, then it's a bug :-)

**Comment by ttulka** [comment]
Maybe you can fix it via a pull request?

**Comment by ad-si** [comment]
Sorry, I'm not working with JavaScript anymore. => Haskell
That even a project as popular and prevalent as request doesn't implement the streaming API correctly says a lot about the ecosystem ^^.

**Comment by davidchappelle** [comment]
There is a hazardous side effect to this bug. In particular, 'finish' indicates when a writable stream has been flushed. I have an issue where trying to run a script after 'end' is emitted results in this:
```
/bin/sh: 1: ./upgrade.sh: Text file busy
```
The root cause appears to be that the script is still not fully written to disk when I try to execute it. That seems pretty crusty. Here are the docs:

    https://nodejs.org/api/stream.html#stream_event_finish

The 'finish' event is emitted after the stream.end() method has been called, and all data has been flushed to the underlying system.

**Comment by ad-si** [comment]
This is still a fundamental bug that *must* be fixed!
