### ISSUE TITLE
node-http-signature 1.2.0 has vulnerable sshpk dependency

### ISSUE THREAD

**Issue by lc3t35** [request/request#2921]
### Summary
request has node-http-signature 1.2.0 dependency, this module has a security issue https://github.com/joyent/node-http-signature/pull/68 

### Expected Behavior
No vulnerability

### Current Behavior
Until node-http-signature has updated his dependency with "sshpk": "^1.7.0", this might be a problem for app using request.

### Possible Solution
Update with fixed node-http-signature

### Context
security issue

### Your Environment
nop

**Comment by benwiggins** [comment]
This is an issue with your own project's package lock file resolving ^1.7.0 to an old version of sshpk.

It has nothing to do with request or node-http-signature.

**Comment by boldt** [comment]
I fixed this issue by removing the `package-lock.json` and by running `npm install` again.

**Comment by nitinsurana** [comment]
@benwiggins Confirmed, it resolves to sshpk 1.7.0 to due to dependency on "http-signature": "~1.2.0".
https://github.com/joyent/node-http-signature/issues/70 - New version of http-signature is not released yet with the fix. 
Solutions: 
1. Fix in my own code using yarn resolutions and/or npm dependencies' dependency (https://stackoverflow.com/a/17423915/566092)
2. Add the above fixes to request module itself - Depends on maintainers, can be done if enough votes I guess unless a new version of `http-signature` is released
3. Fork `http-signature`, fix and release and add that dependency to request module ?!
