### ISSUE TITLE
Content-Length header is not set when using the form library

### ISSUE THREAD

**Issue by mikehaertl** [request/request#316]
I tried to upload a file using the form library like this:

``` javascript
var r = request.post(options, cb),
    form = r.form();

form.append('image', fs.createReadStream('/tmp/testimg.jpg'));
```

My server (nginx as reverse proxy in front of Apache) then throws a `411`. I then tried to set the `Content-Length` manually like this:

``` javascript
var r = request.post(options, cb),
    form = r.form();

form.append('image', fs.createReadStream('/tmp/testimg.jpg'));
r.setHeader('Content-Length', form.getLengthSync());
```

But then the server script (PHP) throws a `UPLOAD_ERR_PARTIAL` (The file was only partially uploaded) error. So i guess, the `Content-Length` is still wrong.

**Comment by Jacob-McKay** [comment]
Yo, 2015 and I've been struggling with this for a few hours now.  I have a npm module that takes a stream, a filename, and a stream length, and writes the stream contents to cloud storage.

I have a server that accepts form uploads, and uses multiparty on the form to pass the file stream, filename, and stream length to the module.

I also have a programmatic client that creates a form (using request.js and form-data) that it uses to upload files to the server, which ultimately end up in cloud storage.

It was really frustrating that a simple html web page with one file input can upload a file to the server which multiparty handles flawlessly, but any programmatic usage of request to create a form post my server has been a PITA.

Even if I set the "knownLength" option on the part that contains my stream, the content-length header for the part is never set, so whenever I try to get the byteCount from multiparty it isn't there because in multiparty land the byteCount comes from the content-length header.  FIRST WORLD PROBLEMS :P 

Anywho, I made a pull-request, felixge/node-form-data#120, for form-data that I tested with my setup and I'm happy with it.  My issue is the content-length not being set on the individual parts, not sure if that's the same issue y'all are having (pretty sure it isn't, but if the PR goes in I'd want to access it via request.js, not form-data directly).

**Comment by danielbprice** [comment]
I also want to say that I'm having the same problem, and I think this should be open.  I want to implement a progress indicator for an upload.  I would love any input about how to do that-- not having content length seems to make it quite tough.

**Comment by qnimate** [comment]
I am using multiparty and request module together. Here is code example:
```
app.post('/submit', function(httpRequest, httpResponse, next){

	var form = new multiparty.Form();

	form.on("part", function(part){
		if(part.filename)
		{

			var FormData = require('form-data');
			var form = new FormData();
			form.append('thumbnail', part);
			
			form.getLength(function(err,length){
				console.log(length);
			    var r = request.post('http://localhost:8888/index.php', { headers: { 'content-length': length } }, function(err, res, body){ 
			    	if(err) {
						return console.error('upload failed:', err);
					}

			    	console.log(body) 
			    });
			     r._form = form
			});
		}
	})

	form.on("error", function(error){
		console.log(error);
	})

	form.parse(httpRequest);	
});
```

Here I am uploading the user uploaded file to another server via streaming i.e., without saving a temporary file.

But on the PHP server no file is uploaded. $_FILES array is empty. 

Please help.

**Comment by Petah** [comment]
+1 still not working...

**Comment by shamasis** [comment]
@mikeal - I have proposed a fix for this on our fork at: https://github.com/postmanlabs/postman-request/pull/13

What do you think? Is it worth a PR here?

**Comment by czardoz** [comment]
@simov ^
