### ISSUE TITLE
Truncating number length in response

### ISSUE THREAD

**Issue by Chronicless** [request/request#3179]
### Summary
Hi there! 
Right now im trying to integrate my app with other system  and one of its  api methods returns large number in the response, but while i tested it in postman and then integrated over request lib in node.js i found that original length of some fields with large numbers were truncated.

POSTMAN response body
{
....
field:1.90720103046081420972429e+23 
...
}

BODY over node.js request
{
.....
field:1.907201030460814e+23
.....
}
As i understand JS read it as number type and truncate due to limit of MAX_SAFE_INTEGER

Are there any clues how to avoid it? Maybe flag to read input as text?
Thanks!

| software         | version
| ---------------- | -------
| request          | 2.79.0
| node             | 8.11.4
| npm              | 5.6.0 
| Operating System | Ubuntu 16.04.5 LTS

**Comment by GeekyDeaks** [comment]
I'm assuming you are using the `json` option to parse the response automatically?

If so, you may need to consider parsing it manually since `JSON.parse()` cannot handle this.

check out:

https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigint
