### ISSUE TITLE
Local JSON file upload using PUT method modifies file.

### ISSUE THREAD

**Issue by suraj021** [request/request#3213]
### Summary

I have to upload a local **JSON** file to the s3 using the s3 public URL. I am using the **PUT** method with **formData** to upload the file. The file is being successfully uploaded but the contents of the file are modified. To be more precise, the contents are appended by the headers of the request.

### Simplest Example to Reproduce

I am using the following code to upload the file.
```js
// Let the name of the file be **test.json**. The contents are as following:
{
    "a": "1",
    "b": "2"
}

// code starts here
const url= 'some s3 path url';
const options = {
    method: 'PUT',
    uri: url,
    headers: {
        'x-amz-acl': 'bucket-owner-full-control'
    },
    formData: {
        file: fs.createReadStream(path.join('./test.json'))
    }
};
request(options, function (error, response, body) {
    if (error) throw new Error(chalk.bold.red(error));
    if (response.statusCode != 200) {
        console.error(JSON.stringify(response.body));
        return;
    }
    console.log(chalk.green.bold(response.statusCode));
})
```

### Expected Behavior

The file should get uploaded to S3.

### Current Behavior

The file gets uploaded to the S3 bucket but the contents inside the file are modified.
The new contents of the file are: 
```js
----------------------------054810111042388555675130
Content-Disposition: form-data; name="file"; filename="test.json"
Content-Type: application/json

{
    "a": "1",
    "b": "2"
}
----------------------------054810111042388555675130--

```

### Possible Solution

I guess the problem is that when I open the stream the headers for the request are written first then the contents?

### Your Environment

| software         | version
| ---------------- | -------
| request          | ^2.88.0
| node             |  11.4.0
| npm              | 6.9.0
| Operating System |

**Comment by gregory-h** [comment]
I had a similar problem in the context of S3 with pre-signed URL's. 

This issue provides a partial answer; 

https://stackoverflow.com/questions/55675275/uploading-file-through-node-request-using-aws-s3-pre-signed-url 

The partial solution is to replace the formData portion with just body:  fs.readFileSync(path.join('./test.json')) and include a content length header, and it worked in my case (PUT to an S3 pre-signed url), but the problem is that the body is presented as a buffer in memory not as a stream, which is undesirable for large files. 

Request docs indicate that body may also be a stream, but in my case setting body to fs.createReadStream(..) produces a Forbidden response, so still looking for a solution to that.
