### ISSUE TITLE
Request never calls callback function when its arrow/anonymus fonction

### ISSUE THREAD

**Issue by benjiben223** [request/request#3266]
I'm trying to make a call to a external API which is hosted locally in my Node.js back-end. I can see that the API receives the request and sends back a response. But when its time to call the callback, if its a anonymous function, it just doesn't call it. But when its a defined function, the callback works. Because of that, I can't get the response at all. I have been trying other function signature, but every time it fails. The only way I can get a response is if I make a mistake and the path is just '/' (it just complains that there is an error, but I at least I get a message).

![image](https://user-images.githubusercontent.com/33231369/73717126-e369b700-46e6-11ea-9165-1fd894bf4474.png)

 
Maybe its a bug, maybe I just don't understand something, but I have been trying for several hours.
BTW, the function is called in a test with mocha, but I don't think it affects anything. Thanks for helping.

**Comment by romellem** [comment]
What are you passing into the `callback` param when you execute `getCourse`?

You are using [a valid format of the main API for Request](https://github.com/request/request/blob/master/index.js#L42). That is, you can call `request` via

```
request(uri, options, callback)
```

So something like this is valid:

```
request(
    'http://localhost',
    {
        headers: { ... },
    },
    function (err, res, body) {
        console.log('The request finished!');
        console.log(err, res, body);
    }
);
```

However, your code is a little confusing because your function `getCourse` accepts a third parameter named `callback`, and then when the _callback_ for the request finishes, you execute the originally passed `callback` with just the `err` param.

This might be easier:

```
/**
 * @param {Function} callback - Executed when the request finished with three arguments: error, response, body
 */
public async getCourse(courseId, authToken, callback) {
  request(
    'http://localhost...',
    { headers: { token: authToken } },
    callback
  );
}
````
