### ISSUE TITLE
Cookie didn't work even if global cookie was enabled

### ISSUE THREAD

**Issue by luoqpolyvi** [request/request#638]
Hi, I'm writing a tool to access [reviewboard](http://www.reviewboard.org/docs/manual/1.7/webapi/2.0/authenticating/#logging-in) by web api,

Here's my code,

```
var request = require('request').defaults({jar: true});

(function connect(){
    request(
        {
            'url' : 'http://review.xxx.com/reviews/',
            'auth': {
                'user': user,
                'pass': pwd,
                'sendImmediately': false
            },
            'jar':true
        },

        function (error, response, body) {
            if( !error && response.statusCode == 200) {
                console.log('Successfully login in');

                getRepos();
            }
        })
})();

function getRepos() {
    request.get('http://review.xxx.com/reviews/api/repositories/', function (err, response, body) {
                    if (err)
                        console.log(response.statusCode);
                });
};
```

I kept getting 401 status code in getRepos(), seems like the cookie didn't work. How to fix it? Thanks

**Comment by twh1808** [comment]
I've actually run into an issue like this, and am in need of assistance. I'm attempting to test a REST API that I created that sits behind Spring Security, so I need authentication to occur first before I can make API calls.

Currently, I stripped my code down to the bare minimum.
```
var request = require('request');
request.defaults({ jar: true });

request.post({
    url: config.baseUrl + '/login',
    form: {
        username: 'foo',
        password: 'bar'
    }
}, function(e1, r1, b1) {
    console.log(r1);
    request.get(config.baseUrl, function(e2, r2, b2) {
        console.log(r2);
    });
});
```
In my authentication success handler, I can see the POST successfully logs in "foo". However, the second GET request redirects me to the sign in page. I've printed out the responses for each of these, and the JSESSIONID is different which is why the redirect to sign in occurs.

I read in the documentation that `jar: true` is for sharing global cookies and is also dependent on `tough-cookie`. I tried adding `var cookie = require('tough-cookie');` as well, with no success.

In addition, I'm hoping that when I resolve this issue that sharing cookies will work with a tool like Chakram. I'd imagine so since Chakram is supposed to just sit on top of the Node request package. Not sure if anyone has experience doing such a thing?
