### ISSUE TITLE
Options object is mutated by calling request

### ISSUE THREAD

**Issue by Janpot** [request/request#857]
I'm trying to run following piece of code:

```
function testUrl(options, callback) {
  request.head(options, function (err, res) {
    if (err || res.statusCode === 405 || res.statusCode === 501) {
      request.get(options, callback);
    } else {
      callback(err, res);
    }
  });
}
```

Unfortunately this makes the HEAD request two times. After the call to `request.head` it seems the options object now has a `method: 'HEAD'` which isn't overriden by the call to `request.get`. I can make it work by not reusing `options` but it seems to me that something like this should work.

**Comment by danielo515** [comment]
This problem is happening currently.
You now use extend, but it is just making a shallow copy, therefore the original object gets mutated.
You should consider using JSON.stringify and parse to make a fast deep clone and get rid of one dependency.

Regards

**Comment by mikeal** [comment]
this *was* fixed. do you have a test that fails for you that exposes this?

**Comment by danielo515** [comment]
Hello @mikeal,
I just read the code and I saw that you use extend, without any option. Extend documentation says that unless you specify the contrary they will make a shallow copy.  Since it is normal to have nested objects on the options object that kind of copy is not enough to ensure that options are not being mutated in any way.

Regards
