### ISSUE TITLE
is there any CORS/ withCredentials support?

### ISSUE THREAD

**Issue by xr** [request/request#986]
i wanna make a CORS request, but i didn't find any options in the readme file.

i just using the jQuery on the client-side, like:

``` js
$.ajax({
                url:'{{url}}',
                type:'GET',
                crossDomain: true,
                xhrFields: {
                    withCredentials: true,
                },
               success:{
               // do sth
               }
})
```

 so I just wonder how to make a cors request using the "request" module. thx.

**Comment by lukehorvat** [comment]
Thanks for the tip, @markbahnman. It looks like the [http-browserify](https://github.com/substack/http-browserify) module erroneously (?) defaults `withCredentials` to `true` (see [this](https://github.com/substack/http-browserify/pull/47) and [this](https://github.com/substack/http-browserify/pull/53)). Since request just passes its options to that module, you have to explicitly set `withCredentials` to `false` in order to override it. :( Hopefully it will be fixed soon for us folks using Browserify + request.

**Comment by blurpis** [comment]
Just wanted to say thank you to everyone who actually posted solutions instead of angrily closing the issue, insisting that request only be used server-side, and sharing patronizing, unhelpful wikipedia links.

**Comment by dandv** [comment]
request is so broken when it comes to [webpack](https://github.com/request/request/issues/1920) and [jspm](https://github.com/request/request/issues/1748) support, that I wish libraries used a [fetch API polyfill for node](https://github.com/github/fetch).
